---
- hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Updating Ubuntu
    apt:
      name: "*"
      state: latest
    tags: update-os
  - name: Install tool-kit
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - htop
      - mosh
      - tmux
      - nfs-kernel-server
  - name: Creating folder for share
    file:
      path: /var/share/
      state: directory
      owner: nobody
      group: nogroup
      mode: 0777
  - name: Updating exports
    lineinfile:
      path: /etc/exports
      line: "/var/share *(rw,insecure,no_subtree_check,no_root_squash)"
      state: present
  - name: Starting the nfs-server
    service:
      name: nfs-kernel-server
      state: started
